# Generated by Django 5.2.16 on 2026-08-01 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_mermaid', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('module_stats', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architecture', to='repos.repository')),
            ],
        ),
        migrations.CreateModel(
            name='PrDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField(blank=True, null=True)),
                ('task_description', models.TextField()),
                ('target_file', models.CharField(max_length=1000)),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('pr_title', models.CharField(blank=True, default='', max_length=500)),
                ('explanation', models.TextField(blank=True, default='')),
                ('diff_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_drafts', to='repos.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('labels', models.JSONField(blank=True, default=list)),
                ('beginner_labeled', models.BooleanField(default=False)),
                ('body_snippet', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('suggested_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='repos.repository')),
            ],
            options={
                'ordering': ['-beginner_labeled', 'id'],
                'unique_together': {('repository', 'issue_number')},
            },
        ),
    ]
