# Generated by Django 5.2.16 on 2026-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturesnapshot',
            name='diagram_mermaid',
        ),
        migrations.AddField(
            model_name='architecturesnapshot',
            name='hld_mermaid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='architecturesnapshot',
            name='lld_mermaid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
