# Generated by Django 5.2.16 on 2026-08-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_remove_architecturesnapshot_diagram_mermaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturesnapshot',
            name='lld_descriptions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
