# Generated by Django 5.2.16 on 2026-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_architecturesnapshot_lld_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturesnapshot',
            name='lld_mermaid',
        ),
        migrations.AddField(
            model_name='architecturesnapshot',
            name='lld_diagrams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
