# Generated by Django 5.2.16 on 2026-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_remove_architecturesnapshot_lld_mermaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturesnapshot',
            name='hld_group_diagrams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
