# Generated by Django 5.2.16 on 2026-08-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0005_architecturesnapshot_hld_group_diagrams'),
        ('repos', '0002_alter_repository_unique_together_repository_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_file', models.CharField(max_length=1000)),
                ('task_description', models.TextField(blank=True, default='')),
                ('test_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('framework', models.CharField(blank=True, default='', max_length=100)),
                ('explanation', models.TextField(blank=True, default='')),
                ('test_code', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drafts', to='repos.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
