# Generated by Django 5.2.16 on 2026-08-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField()),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file_tree', models.JSONField(blank=True, default=list)),
                ('chunk_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True, default='')),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_job', to='repos.repository')),
            ],
        ),
    ]
