# Generated by Django 5.2.16 on 2026-08-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_alter_repository_unique_together_repository_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_indexed_commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
