# Generated by Django 5.2.16 on 2026-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_repository_last_indexed_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
