# Generated by Django 5.2.16 on 2026-08-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_repository_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='scoped_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
